---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/
  commands:
  - docker ps -a

volumes:
- name: dockersock
  host:
    path: /var/run/