---
kind: pipeline
type: kubernetes
name: pet pipeline

steps:

- name: compile
  image: maven:3-jdk-11-slim
  commands:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

- name: build image
  image: cloudzune/drone-kaniko
  settings:
    registry: hub.docker.com
    dockerfile: Dockerfile
    cache: true
    skip_tls_verify: true
    username:
      from_secret: username
    password:
      from_secret: password
    repo: k8s/pet
    tags: latest